### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

### ISSUE THREAD

**Issue by LuckyPigoen** [gautamkrishnar/socli#107]
When I use socli, and this message occurred, how can I fixed it?

Traceback (most recent call last):
  File "/usr/local/bin/socli", line 11, in <module>
    load_entry_point('socli==3.6', 'console_scripts', 'socli')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/socli/socli.py", line 13, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by SuperMeepBoy** [comment]
I was just watching the project. I haven't used it at the moment so I can't help you but you might want to tell people what command you typed to help them investigate on the issue. Even if it's not useful in this particular case (again, I don't know, maybe it is !) it's a good habit to tell people what you did and what result you have. :)

**Comment by LuckyPigoen** [comment]
Hey there, thanks for you telling me the tip, here's the command I use with socli, I just type "socli", and then the wrong msg occurred, so I think I need help, because I can't use socli to do anything, I've tried to installed it again, but it won't work, and as I put any keyword or any argument or even left it a blank, it will show the same error message. Thanks

**Comment by mohamedotnet** [comment]
@LuckyPigoen try this: socli.py -u 1

**Comment by LuckyPigoen** [comment]
@mohamedotnet  I got the same error when using socli -u 1. Thanks
