### ISSUE TITLE
install error  'cp949' codec can't decode byte 0xe2 in position 16534: illegal multibyte sequence

### ISSUE THREAD

**Issue by mindgitrwx** [gautamkrishnar/socli#143]
Windows 10, `easy_install socli` make this errorkk

install error  'cp949' codec can't decode byte 0xe2 in position 16534: illegal multibyte sequence

Detailed error logs are like this.
Python version is 3.6.5
Even makes error 

```
Searching for socli
Reading https://pypi.org/simple/socli/
Downloading https://files.pythonhosted.org/packages/79/68/614425c81c1a0ba827148841f72e9762a39d82a351e956c1af3002bc1863/socli-3.6.tar.gz#sha256=cf50b17f4032aa0488876febff4714ae49252e99cc4d9a80836bbdddac927d5c
Best match: socli 3.6
Processing socli-3.6.tar.gz
Writing C:\Users\jonghyun\AppData\Local\Temp\easy_install-yzcuw6ar\socli-3.6\setup.cfg
Running socli-3.6\setup.py -q bdist_egg --dist-dir C:\Users\jonghyun\AppData\Local\Temp\easy_install-yzcuw6ar\socli-3.6\egg-dist-tmp-hb87flbh
Traceback (most recent call last):
  File "c:\python\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
    yield saved
  File "c:\python\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
    yield
  File "c:\python\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "c:\python\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "C:\Users\jonghyun\AppData\Local\Temp\easy_install-yzcuw6ar\socli-3.6\setup.py", line 14, in <module>
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 16534: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\easy_install.exe\__main__.py", line 9, in <module>
  File "c:\python\lib\site-packages\setuptools\command\easy_install.py", line 2312, in main
    **kw
  File "c:\python\lib\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "c:\python\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "c:\python\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "c:\python\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "c:\python\lib\site-packages\setuptools\command\easy_install.py", line 412, in run
    self.easy_install(spec, not self.no_deps)
  File "c:\python\lib\site-packages\setuptools\command\easy_install.py", line 673, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "c:\python\lib\site-packages\setuptools\command\easy_install.py", line 699, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "c:\python\lib\site-packages\setuptools\command\easy_install.py", line 884, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "c:\python\lib\site-packages\setuptools\command\easy_install.py", line 1152, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "c:\python\lib\site-packages\setuptools\command\easy_install.py", line 1138, in run_setup
    run_setup(setup_script, args)
  File "c:\python\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
    raise
  File "c:\python\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\python\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
    yield
  File "c:\python\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\python\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "c:\python\lib\site-packages\setuptools\sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "c:\python\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "c:\python\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
    yield saved
  File "c:\python\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
    yield
  File "c:\python\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "c:\python\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "C:\Users\jonghyun\AppData\Local\Temp\easy_install-yzcuw6ar\socli-3.6\setup.py", line 14, in <module>
```

pip install socli also makes error. error logs are like this.

```
Python 3.6.5
PS D:\study\vimplugin> pip install socli
Collecting socli
  Using cached https://files.pythonhosted.org/packages/79/68/614425c81c1a0ba827148841f72e9762a39d82a351e956c1af3002bc1863/socli-3.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jonghyun\AppData\Local\Temp\pip-install-4fcdc1o7\socli\setup.py", line 14, in <module>
        longd = f.read()
    UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 16534: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\jonghyun\AppData\Local\Temp\pip-install-4fcdc1o7\socli\
```

**Comment by such-doge** [comment]
I know this is a month late, but the issue is an extended-ASCII "right single quotation mark" in README.rst, which makes it incompatible with any code page that can't interpret it. This is an issue for Windows installed with a language that uses non-Latin characters. Since Windows uses the default code page for the system locale/language in the command prompt rather than UTF-8, you will need to change your command prompt's locale to UTF-8. Type `chcp 65001` into Powershell to switch to UTF-8 before you run easy_install.

**Comment by hedythedev** [comment]
@mindgitrwx are you still having the issue? Try the newer releases. If so open a new issue with the latest error info, thank you.
By the way the socli interactive mode is currently not working for Windows you can see #185
