### ISSUE TITLE
socli -iq is broken

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/socli#201]
`socli -iq` is not working as expected, question selection after the listing is broken.

**Comment by Saif807380** [comment]
Can I go ahead and give this a try?

**Comment by gautamkrishnar** [comment]
Yes @Saif807380 you can. Following is the trace when running the cli in --debug mode. `socli -iq for loop in python --debug`

```bash

Traceback (most recent call last):
  File "/usr/local/Cellar/socli/5.5/libexec/lib/python3.8/site-packages/socli/search.py", line 355, in socli_interactive
    socli.tui.MAIN_LOOP.run()
  File "/usr/local/Cellar/socli/5.5/libexec/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/local/Cellar/socli/5.5/libexec/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/local/Cellar/socli/5.5/libexec/lib/python3.8/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/usr/local/Cellar/socli/5.5/libexec/lib/python3.8/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/usr/local/Cellar/socli/5.5/libexec/lib/python3.8/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/usr/local/Cellar/socli/5.5/libexec/lib/python3.8/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/Cellar/socli/5.5/libexec/lib/python3.8/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/local/Cellar/socli/5.5/libexec/lib/python3.8/site-packages/socli/tui.py", line 59, in process_input
    super(EditedMainLoop, self).process_input(keys)
  File "/usr/local/Cellar/socli/5.5/libexec/lib/python3.8/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/Cellar/socli/5.5/libexec/lib/python3.8/site-packages/socli/search.py", line 325, in keypress
    self.select_question(question_url, int(key))
  File "/usr/local/Cellar/socli/5.5/libexec/lib/python3.8/site-packages/socli/search.py", line 340, in select_question
    question_title, question_desc, question_stats, answers = get_question_stats_and_answer_and_comments(url)
ValueError: too many values to unpack (expected 4)
```

**Comment by Saif807380** [comment]
Thanks for the traceback. Seems like a data unpacking issue. I'm on it.

**Comment by hedythedev** [comment]
Just a reminder, there are more than one references to `get_question_stats_and_answer_and_comments` that needs to be updated for unpacking the tuple:
* search.py line 340 (shown in trace back from @gautamkrishnar)
https://github.com/gautamkrishnar/socli/blob/dcc90be554ce502e3a3e91d28961ad9c67fb77ac/socli/search.py#L340
* socli.py line 283-284
https://github.com/gautamkrishnar/socli/blob/dcc90be554ce502e3a3e91d28961ad9c67fb77ac/socli/socli.py#L283-L284

Complete tuple should be of
`( question_title, question_desc, question_stats, answers, comments, dup_url )`

If an item of the tuple is uneeded you can use `_` to prevent having unused variables, for example in socli.py it can be:
```python
question_title, question_desc, question_stats, answers, comments, _ = \ 
     search.get_question_stats_and_answer_and_comments(url) 
```

**Comment by gautamkrishnar** [comment]
Thanks for the pointer @hedythedev 👍
