### ISSUE TITLE
Unsupported Locale setting 

### ISSUE THREAD

**Issue by CarloCattano** [gautamkrishnar/socli#204]
Hello there . Wonderful & exciting project . 
Im getting this error when trying to use it after installation .

> C:\Windows\system32>socli -u
Traceback (most recent call last):
  File "c:\users\freev\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\freev\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\freev\AppData\Local\Programs\Python\Python38\Scripts\socli.exe\__main__.py", line 4, in <module>
  File "c:\users\freev\appdata\local\programs\python\python38\lib\site-packages\socli\socli.py", line 14, in <module>
    import urwid
  File "c:\users\freev\appdata\local\programs\python\python38\lib\site-packages\urwid\__init__.py", line 26, in <module>
    from urwid.widget import (FLOW, BOX, FIXED, LEFT, RIGHT, CENTER, TOP, MIDDLE,
  File "c:\users\freev\appdata\local\programs\python\python38\lib\site-packages\urwid\widget.py", line 27, in <module>
    from urwid.util import (MetaSuper, decompose_tagmarkup, calc_width,
  File "c:\users\freev\appdata\local\programs\python\python38\lib\site-packages\urwid\util.py", line 61, in <module>
    detected_encoding = detect_encoding()
  File "c:\users\freev\appdata\local\programs\python\python38\lib\site-packages\urwid\util.py", line 58, in detect_encoding
    locale.setlocale(locale.LC_ALL, initial)
  File "c:\users\freev\appdata\local\programs\python\python38\lib\locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by gautamkrishnar** [comment]
@CarloCattano please try this: https://stackoverflow.com/a/36257050, It is your environment issue, not the issue with socli.

**Comment by gautamkrishnar** [comment]
@CarloCattano since you are using windows try this https://stackoverflow.com/a/956084/4214976. Sorry for sharing you the Linux way of doing it.

**Comment by gautamkrishnar** [comment]
@CarloCattano can you please try the same in the powershell instead of cmd?

**Comment by gautamkrishnar** [comment]
We can fix this by not importing urwid on windows.

**Comment by gautamkrishnar** [comment]
Urwid already have a fix for this implemented https://github.com/urwid/urwid/commit/fd010f8336407ad1a42522b424d2ea7b7800ebc4 @CarloCattano can you please share the output of `pip freeze` command here.

**Comment by gautamkrishnar** [comment]
stale issue, closing. Please reopen if you are still experiencing this.
