### ISSUE TITLE
python3.11 breaks socli

### ISSUE THREAD

**Issue by MartyLake** [gautamkrishnar/socli#296]
## 🐛 Bug Report

```
$ socli
Traceback (most recent call last):
  File "/opt/homebrew/bin/socli", line 5, in <module>
    from socli.sentry import main
  File "/opt/homebrew/lib/python3.11/site-packages/socli/sentry.py", line 5, in <module>
    sentry_sdk.init(
  File "/opt/homebrew/lib/python3.11/site-packages/sentry_sdk/hub.py", line 121, in _init
    client = Client(*args, **kwargs)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sentry_sdk/client.py", line 143, in __init__
    self._init_impl()
  File "/opt/homebrew/lib/python3.11/site-packages/sentry_sdk/client.py", line 223, in _init_impl
    self.integrations = setup_integrations(
                        ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sentry_sdk/integrations/__init__.py", line 109, in setup_integrations
    for integration_cls in iter_default_integrations(
  File "/opt/homebrew/lib/python3.11/site-packages/sentry_sdk/integrations/__init__.py", line 41, in iter_default_integrations
    yield getattr(import_module(module), cls)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sentry_sdk/integrations/tornado.py", line 30, in <module>
    from tornado.web import RequestHandler, HTTPError
  File "/opt/homebrew/lib/python3.11/site-packages/tornado/web.py", line 86, in <module>
    from tornado import httputil
  File "/opt/homebrew/lib/python3.11/site-packages/tornado/httputil.py", line 106, in <module>
    class HTTPHeaders(collections.MutableMapping):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

might be caused by 

> Remove deprecated aliases to [Collections Abstract Base Classes](https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes) from the collections module. (Contributed by Victor Stinner in bpo-37324.)

(saw in SO https://stackoverflow.com/questions/72032032/importerror-cannot-import-name-iterable-from-collections-in-python )

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/gautamkrishnar/socli/blob/master/CONTRIBUTING.md)?

Sure, I know how to use git and write basic python one liners, but this step

```
5. Make changes in source code/ project.
```

I don’t know how to do because I don’t know how to run the local socli from its source directory. If you could add to the README instructions on how to setup a local development environ, I would be happy to try to fix it.

**Comment by this-is-geek-sassy** [comment]
I could observe the issue in the Python 3.12 environment as well. However, the command is breaking with another exception. It looks somewhat like this: 
`C:\Windows\System32>socli
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\AVWUVT744\AppData\Local\Programs\Python\Python312\Scripts\socli.exe\__main__.py", line 4, in <module>
  File "C:\Users\AVWUVT744\AppData\Local\Programs\Python\Python312\Lib\site-packages\socli\sentry.py", line 12, in <module>
    main()
  File "C:\Users\AVWUVT744\AppData\Local\Programs\Python\Python312\Lib\site-packages\socli\socli.py", line 474, in main
    printer.helpman()
  File "C:\Users\AVWUVT744\AppData\Local\Programs\Python\Python312\Lib\site-packages\socli\printer.py", line 195, in helpman
    screen_height, screen_width = subprocess.check_output(['stty', 'size']).split()
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AVWUVT744\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AVWUVT744\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AVWUVT744\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\stdlib.py", line 217, in sentry_patched_popen_init
    rv = old_popen_init(self, *a, **kw)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AVWUVT744\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\AVWUVT744\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-Break to quit`

**Comment by MartyLake** [comment]
@this-is-geek-sassy well, the error is gone after updating all homebrew packages now.
