### ISSUE TITLE
Throwing error in windows

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/socli#39]
SoCLI is throwing an error while it is using the interactive mode in windows...

![image](https://cloud.githubusercontent.com/assets/8397274/24820553/4b0df334-1c07-11e7-9bd3-02397337b264.png)

Debug output:
```bash
C:\Users\Gautam krishna R\PycharmProjects\socli>python -m socli --debug -iq hello world java
Error name: Name not found globally.

Description: name 'fcntl' is not defined

Traceback (most recent call last):
  File "C:\Users\Gautam krishna R\PycharmProjects\socli\socli\socli.py", line 483, in socli_interactive
    LOOP = urwid.MainLoop(QUESTION_PAGE, palette)
  File "C:\Program Files\Python35\lib\site-packages\urwid\main_loop.py", line 111, in __init__
    screen = raw_display.Screen()
  File "C:\Program Files\Python35\lib\site-packages\urwid\raw_display.py", line 89, in __init__
    fcntl.fcntl(self._resize_pipe_rd, fcntl.F_SETFL, os.O_NONBLOCK)
NameError: name 'fcntl' is not defined
exiting...
```
We need to implement the standard interactive mode in windows... @e-beach

**Comment by gautamkrishnar** [comment]
Cause: https://github.com/urwid/urwid/issues/152
