### ISSUE TITLE
Windows: "Failed to create process" when running `socli` without parameters

### ISSUE THREAD

**Issue by JonasGroeger** [gautamkrishnar/socli#6]
PS C:\Users\jonas> pip install socli
Requirement already satisfied (use --upgrade to upgrade): socli in c:\program files\python35-64\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): BeautifulSoup4 in c:\program files\python35-64\lib\site-packages (from socli)
Requirement already satisfied (use --upgrade to upgrade): requests in c:\program files\python35-64\lib\site-packages (from socli)
PS C:\Users\jonas> socli
failed to create process.
PS C:\Users\jonas> ($env:Path).Replace(';',"`n")
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Program Files (x86)\GNU\GnuPG\pub
C:\Users\jonas\bin
C:\Users\jonas\AppData\Local\atom\bin
C:\Program Files\Python35-64\
C:\Program Files\Python35-64\Scripts\
C:\ProgramData\Oracle\Java\javapath
C:\Program Files\Git\cmd
C:\Program Files\Inkscape
C:\Program Files\Rapid Environment Editor
C:\Program Files\Sublime Text 3
C:\HashiCorp\Vagrant\bin
C:\Program Files\7-Zip
C:\Program Files (x86)\Vim\vim74
C:\Users\jonas\bin\kitty
C:\Program Files\MikTex\miktex\bin\x64\
C:\Program Files\ffmpeg\bin

**Running `python -m socli` works btw.**

**Comment by gautamkrishnar** [comment]
:+1:  thanks i will try to fix it..

**Comment by gautamkrishnar** [comment]
It is actually a windows python bug. See:
http://stackoverflow.com/questions/24627525/fatal-error-in-launcher-unable-to-create-process-using-c-program-files-x86
http://stackoverflow.com/questions/31808180/installing-pyinstaller-via-pip-leads-to-failed-to-create-process
http://stackoverflow.com/questions/17373265/pip-easy-install-failure-failed-to-create-process


It has a workaround implemented suggested by @tomduck on https://github.com/pypa/pip/issues/2783

I am trying to implement it to socli...

@tomduck can you help me in implementing it?

**Comment by gautamkrishnar** [comment]
@JonasGroeger  you can try using easy install
```
easy_install socli
```

**Comment by Sukhada11** [comment]
I am use any feature on windows .
I have installed socli successfully
_D:\Python\socli>pip install socli
Requirement already satisfied: socli in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages\socli-3.6-py3.6.egg
Requirement already satisfied: BeautifulSoup4 in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages (from socli)
Requirement already satisfied: requests in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages (from socli)
Requirement already satisfied: colorama in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages (from socli)
Requirement already satisfied: Py-stackExchange in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages (from socli)
Requirement already satisfied: urwid in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages (from socli)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages (from requests->socli)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages (from requests->socli)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages (from requests->socli)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages (from requests->socli)
Requirement already satisfied: six>=1.8.0 in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages (from Py-stackExchange->socli)

D:\Python\socli>socli
Traceback (most recent call last):
  File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\Scripts\socli-script.py", line 11, in <module>
    load_entry_point('socli==3.6', 'console_scripts', 'socli')()
  File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "D:\Python\socli\socli\socli.py", line 200
    UnicodeText(u'\u2191: previous answer, \u2193: next answer, o: open in browser, \u2190: back, q: quit').encode('utf-8'))
                                                                                                                           ^
SyntaxError: invalid syntax

D:\Python\socli>socli -u
Traceback (most recent call last):
  File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\Scripts\socli-script.py", line 11, in <module>
    load_entry_point('socli==3.6', 'console_scripts', 'socli')()
  File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "D:\Python\socli\socli\socli.py", line 200
    UnicodeText(u'\u2191: previous answer, \u2193: next answer, o: open in browser, \u2190: back, q: quit').encode('utf-8'))
                                                                                                                           ^
SyntaxError: invalid syntax

D:\Python\socli>socli -h
Traceback (most recent call last):
  File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\Scripts\socli-script.py", line 11, in <module>
    load_entry_point('socli==3.6', 'console_scripts', 'socli')()
  File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "D:\Python\socli\socli\socli.py", line 200
    UnicodeText(u'\u2191: previous answer, \u2193: next answer, o: open in browser, \u2190: back, q: quit').encode('utf-8'))
                                                                                                                           ^
SyntaxError: invalid syntax

D:\Python\socli>
_
