### ISSUE TITLE
Needs testers: Release Version 3.7

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/socli#93]
I am planning to release **SoCLI 3.7** we need to make sure that all the features of SoCLI are working fine on the following platforms:

- [X]  Windows : #84 **Tested**
- [x]  Linux: 
- [x]  Mac: 

### How can you help?
We need testers to make sure that the SoCLI is working fine on the above platforms:
* Comment on this issue and let everyone know that you are testing. :smile: 
* Just clone SoCLI. You must have Git, Python and PIP installed. Type the following commands.
```bash
git clone https://github.com/gautamkrishnar/socli.git
cd socli
git checkout develop
```
* Install the socli development version.
```bash
sudo pip install -r requirements.txt
sudo python setup.py install
```
* Now you can use socli command on your shell.
Just execute the sample commands in the readme: https://github.com/gautamkrishnar/socli#usage and check whether everything is working fine. If you are facing any issues, don't forget to comment here so that we can fix it :hocho: :smile: 
* Just comment on this thread and let me know whether it is working fine.

**Comment by cbarillas** [comment]
Hi, this is my first time contributing to an open source project. I ran all the commands in the readme and everything worked fine on Linux (Ubuntu 16.04). However, in your readme, for the command `socli -t javascript,node.js -q window.open` there should be a space after the comma. Without it I get "No results found..." Other than that, all the commands worked well. Very cool CLI by the way!

**Comment by prashantchahal26** [comment]
The keys for next, previous and back are not shown in interactive query when I am running Socli on my Mac. Although it works fine using up, down, left and right key but the help options are shown wrong. It just displays " ?: ".

**Comment by cbarillas** [comment]
For me it just shows the option `0-9: select a question, any other key: exit` The arrows work fine when you select a question. The help command also works for me.

**Comment by gautamkrishnar** [comment]
@prashantchahal26 thanks for taking your time testing it, Please recheck whether the issue still exists in your develop branch. Just use the following command to pull the latest changes:
```
git pull
```

**Comment by prashantchahal26** [comment]
0:54: execution error: "http://stackoverflow.com/questions/ask" doesn’t understand the “open location” message. (-1708)
Still has the same error.

**Comment by dzulfahmi** [comment]
I have try to install it on ubuntu 16.04 using python 2.7
When I run this command sudo pip install requirements.txt, there was some message:
  Could not find a version that satisfies the requirement requirements.txt (from versions: )
  No matching distribution found for requirements.txt
Then, when I run command sudo python setup.py install, there is run well
I have tried all function in https://github.com/gautamkrishnar/socli#usage and it run well.

**Comment by LySofDev** [comment]
Lenovo Yoga 910 - Solus 3 (Linux 4.13.5)

Cloned the repository and setup a virtual environment:

```
git clone https://github.com/gautamkrishnar/socli.git
cd socli
python -m venv venv
source venv/bin/activate
```

Tried running:
```
pip install requirements.txt
```

 but receive this error:
```
Collecting requirements.txt
   Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt
```

Ignored error and ran:
```
python setup.py install
```

All commands worked.

**Comment by gautamkrishnar** [comment]
@LySofDev thanks. Please use `pip install -r requirements.txt` to install the requirements. My bad, I specified it as `pip install requirements.text` in the issue. It is now updated. Thanks for letting me know that everything works fine.

**Comment by sebastianseitz** [comment]
Tested in on macOS 10.12.6 and python 2.7.14, everything seems to work as intended.

**Comment by sebastianseitz** [comment]
Comment to the issue description:
- Please do not encourage users to use `sudo pip` to install dependencies, this is discouraged (https://stackoverflow.com/questions/21055859/what-are-the-risks-of-running-sudo-pip)
- Telling people to setup a virtual environment for socli would be helpful (and avoid the sudo issue)

**Comment by rebeccamorgan** [comment]
I've been testing on macOS 10.13 and Python 2.7.14, and noticed that for users who haven't done any questioning or answering the URLError exception failed in Python 2. I have submitted #105 to change this import depending on version and re-structure the stats printed when there are no questions/answers returned. Thanks!

**Comment by sramakrishnan247** [comment]
Tested on Ubuntu 17.04. Everything seems to work fine.

**Comment by FredMougel** [comment]
Hello,
This is my very first collaboration as a newbie.
I have installed socli on ArchLinux with kernel 4.13.12-1-ARCH. The install went fine but I have an error message everytime I try one of the search suggestions:

```
[fred@ArchFred socli]$ socli for loop in python syntax
Traceback (most recent call last):
  File "/usr/bin/socli", line 11, in <module>
    load_entry_point('socli==3.6', 'console_scripts', 'socli')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2749, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2402, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1131, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1112, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 544, in spec_from_file_location
  File "/usr/lib/python3.6/site-packages/socli-3.6-py3.6.egg/socli/socli.py", line 200
    UnicodeText(u'\u2191: previous answer, \u2193: next answer, o: open in browser, \u2190: back, q: quit').encode('utf-8'))
                                                                                                                           ^
SyntaxError: invalid syntax
```
Does it have to do with the Python version?
```
[fred@ArchFred socli]$ python --version
Python 3.6.3
```

**Comment by gautamkrishnar** [comment]
@fredmougel thanks for reporting... Its not related to python version. Its a syntax error. Will look into it soon...

**Comment by Sukhada11** [comment]
I am use any feature on windows .
I have installed socli successfully...None of the usage worked for me on Windows 10-64 bit.
_D:\Python\socli>pip install socli
Requirement already satisfied: socli in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages\socli-3.6-py3.6.egg
Requirement already satisfied: BeautifulSoup4 in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages (from socli)
Requirement already satisfied: requests in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages (from socli)
Requirement already satisfied: colorama in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages (from socli)
Requirement already satisfied: Py-stackExchange in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages (from socli)
Requirement already satisfied: urwid in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages (from socli)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages (from requests->socli)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages (from requests->socli)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages (from requests->socli)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages (from requests->socli)
Requirement already satisfied: six>=1.8.0 in c:\users\welcome\appdata\local\programs\python\python36-32\lib\site-packages (from Py-stackExchange->socli)

D:\Python\socli>socli
Traceback (most recent call last):
File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\Scripts\socli-script.py", line 11, in 
load_entry_point('socli==3.6', 'console_scripts', 'socli')()
File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources_init_.py", line 565, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources_init_.py", line 2631, in load_entry_point
return ep.load()
File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources_init_.py", line 2291, in load
return self.resolve()
File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources_init_.py", line 2297, in resolve
module = import(self.module_name, fromlist=['name'], level=0)
File "D:\Python\socli\socli\socli.py", line 200
UnicodeText(u'\u2191: previous answer, \u2193: next answer, o: open in browser, \u2190: back, q: quit').encode('utf-8'))
^
SyntaxError: invalid syntax

D:\Python\socli>socli -u
Traceback (most recent call last):
File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\Scripts\socli-script.py", line 11, in 
load_entry_point('socli==3.6', 'console_scripts', 'socli')()
File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources_init_.py", line 565, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources_init_.py", line 2631, in load_entry_point
return ep.load()
File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources_init_.py", line 2291, in load
return self.resolve()
File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources_init_.py", line 2297, in resolve
module = import(self.module_name, fromlist=['name'], level=0)
File "D:\Python\socli\socli\socli.py", line 200
UnicodeText(u'\u2191: previous answer, \u2193: next answer, o: open in browser, \u2190: back, q: quit').encode('utf-8'))
^
SyntaxError: invalid syntax

D:\Python\socli>socli -h
Traceback (most recent call last):
File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\Scripts\socli-script.py", line 11, in 
load_entry_point('socli==3.6', 'console_scripts', 'socli')()
File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources_init_.py", line 565, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources_init_.py", line 2631, in load_entry_point
return ep.load()
File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources_init_.py", line 2291, in load
return self.resolve()
File "C:\Users\WELCOME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources_init_.py", line 2297, in resolve
module = import(self.module_name, fromlist=['name'], level=0)
File "D:\Python\socli\socli\socli.py", line 200
UnicodeText(u'\u2191: previous answer, \u2193: next answer, o: open in browser, \u2190: back, q: quit').encode('utf-8'))
^
SyntaxError: invalid syntax

D:\Python\socli>
_

**Comment by dattadebrup** [comment]
Hi, this is my first  attempt in an open source project.I tried to install socli on `Windows 10 `as per the instructions given above but it failed to install 'urwid' with the error message `ValueError: Unknown MS Compiler version 1900`. Since urwid is not available for windows I think we have to use an alternative module for windows compatibility.Please let me know if any one else is working on this issue and how much he/she has progressed.

**Comment by gautamkrishnar** [comment]
Thanks a lot for the input everyone. We will release the new version soon after fixing all this bugs.
